<a href="https://colab.research.google.com/github/jesspaulillo/data-science-/blob/main/Copy_of_Jess_Paulillo_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100): # when you run this, a lost of numbers from 0 to 100 will appear
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
for i in range(5,8): #when you run this, a list of numbers between 5 and 8 will appear without including 8
    print(i)

5
6
7


In [ ]:
for i in range(3): # a list of numbers between 0-3, not including 3 
    print( "Test Number: " , i ) # labeling "Test Number" before stating each number

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x): # defining the words to equal the equation 
    return x**2 # squarring an x

In [ ]:
square(5) # squarring 5, 5(5) = 25

25

In [ ]:
square(square(2)) # 2 squarred times 2 squarred 

16

In [ ]:
square(square(square(2)))
# 2 squarred 3 times which equals 256

256

In [ ]:
square(123456) #squarring 123456

15241383936

In [ ]:
square(square(5)) # squarring 5 squarrred 

625

In [ ]:
def add_two(x): # defining that 2 will be added to x 
    return x+2 # when ran it will equl this 

In [ ]:
add_two(5) #adding 2 to 5 

7

In [ ]:
square(add_two(5)) # sqaurring 5 +2=7, (7*7)

49

### Logical Branching

In [ ]:
choice = "apple" # creating an element to equal "apple"

In [ ]:
if choice == "apple": # showing that the word choice is representing the word apple 

    print("You choose apples.")
#the line when ran 
else:
    
    print("You did not choose apples.") # the other option or choice 

You choose apples.


In [ ]:
choice = "orange" # creating an element to create "orange" 

In [ ]:
if choice == "apple": # using the code to make the word "apple"

    print("You choose apples.") # the line after running it through

else: 
    
    print("You did not choose apples.") #the code for not using apples 

You did not choose apples.


In [ ]:
choice = "apple" # creating an element to display the word apple 

In [ ]:
if choice == "apple": #displaying the word apple

    print("You choose apples.") #displaying a code to produce the word "apple"
    print("Thank you, shop again!") # a code to produce this line to say "Thank you, shop again!"
    print(2**123) # squarring 123

elif choice == "orange": # used if the statement is not true, checking for another condition 

    print("You choose oranges.") #the line, else if, showing another option like "oranges"
    print("Thank you, shop again!")# starting a new line after "you choose oranges"

else:
    
    print("You did not choose apples or oranges.")#displaying a code for not choosing either apples nor oranges 
    print("Thank you, shop again!") 

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #any entry in a form to begin code

Please enter your choice (i.e. apple): oranges


In [ ]:
choice #signaling an option 

'oranges'

In [ ]:
if choice == "apple": #using apple as a choice to program 

    print("You choose apples.") #apple used in  a code 

elif choice == "oranges": #checking for another condition 

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") #neither options are compatible 

You choose oranges.


#### Coins

In [ ]:
np.random.random() # starting off with first componenent of the line 

In [ ]:
np.random.random() > 0.5 #showing any random number is less than 0.5

In [ ]:
def flip_coin(): #showing a sequence of options when a coin is flipped
    if np.random.random() > 0.5: #one of the options is greater than o.5 
        print("Heads") #heads would be shown if it was greater than 0.5 
    else:
        print("Tails") #the opposite option 

In [ ]:
flip_coin() #the action in getting a random number

### Graphics Output

In [ ]:
from IPython.core.display import display, HTML # display syntax-highlighted source code

In [ ]:
display(HTML('<h1>Hello, world!</h1>')) #a code to make "hello world"

In [ ]:
def coin(): # a line to make a certaimn side of coing 
  return np.random.randint(2) # Python is used to return random values from a uniform ditribution 

In [ ]:
coin() # starting line

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) # displaying a link for coin flip

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #link for heads
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #link for tails 

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) # code to show image 

In [ ]:
show_img(heads) #when ran it shows heads 

In [ ]:
show_img(tails) #when ran it shows tails 

In [ ]:
def flip_coin(): #starting line 
 
    if coin(): #primary choice in displaying heads
        show_img(heads)
    else: #showing alternative option when coin is flipped 
        show_img(tails)

In [ ]:
flip_coin()

In [ ]:
for i in range(5): #giving a sequence of numbers up until reaching the number 5 
    flip_coin() #flipping a coin to reach that sequence 

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [ ]:
def shuffle(x): #shuffling to display a sequence
    for i in range(len(x)-1,0,-1): #displaying options that range betwen -1 and 0
        j = np.random.randint(0,i+1) # random code 
        x[i],x[j] = x[j],x[i]
        # print(j,x) # a code to run to display a range of numbers along with x 
    return x #code to run 

In [ ]:
a = np.arange(52) #return evenly spaced values within a given interval of 52

In [ ]:
shuffle(a) # code to shuffle to give a sequence of numbers 

In [ ]:
np.random.permutation(52) #randomly permute a sequnce, or return a permuted range 

### Speed Test

In [ ]:
%%timeit #showing speed test 
shuffle(a)

In [ ]:
%%timeit
np.random.permutation(52)

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52) #given a random list of 52 numbers in a random order when ran 

array([51, 40, 39,  2, 19, 24, 12,  7, 14, 28,  8, 21, 18, 49, 47, 27,  1,
       44, 10, 16, 42,  3, 43, 31, 46, 29, 38,  4, 23,  5, 50, 35, 41, 36,
       11, 13, 34, 15, 32, 26, 45, 20, 48, 30,  9, 17, 33,  0, 22, 25,  6,
       37])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards

array([32,  0, 51, 29, 27, 15, 39, 45, 42, 12, 30, 28, 44, 34, 33, 16, 49,
       47,  6, 22, 40, 24, 10, 21, 11, 23, 41, 48,  5, 36, 13, 46, 31, 17,
        7, 14,  1, 26,  2, 43, 25,  4, 35, 18,  8, 37, 50,  9,  3, 38, 20,
       19])

In [ ]:
cards[0] #showing that random numbers are given when ran 

32

In [ ]:
cards[1]

0

In [ ]:
cards[2]

51

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) #a list of 52 random numbers 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #shaping an array without changing data 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 #putting numbers a sequential order 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #displaying the options for suits
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #displaying options for names

In [ ]:
def card_name(card_number): #putting together suits and name 
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0) #suits and names put together to give random code

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) 

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5): #makimng a code to contain both suits and names into a single line 
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l'] #showing the possibilites of suits 
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4) #returning integers from 4 
j = np.random.randint(13) #random integers of 13

In [ ]:
i,j

(0, 11)

In [ ]:
suit[i] #displaying suits with a letter

'k'

In [ ]:
card[j]

'q'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img): #code to display an image 
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3) #specifying s acode to make a specific card containing those components 

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)